### ISSUE TITLE
Spike: Verified Signatures for  QG Commits

### ISSUE THREAD

**Issue by Githubbubber** [QueerGlobal/qg-docs#8]
## 🧑🏽 Story

We need an **Added Security Measure** 
to **Be Implemented from a Contributor’s GitHub Account** 
in order for a **Developer from an Outside Organization** 
to **Contribute to QG Code Repositories**.

## Epic

N/A

 

## 🔨✔️ Acceptance Criteria

- Write up a Spike with at least two reasons for verified sigs. Each reason must add value to the overall codebase.
- The Spike will have sections for the following:
- -> Description
- -> Instructions
- -> Next Steps
- Add a link to the Spike from my personal GH account

## For More Info

#️⃣Slack: "Meke (Mickey) - She/her/cornball"

**Comment by mnyon-grandkru** [comment]
Here are two reasons for people to verify:
* SSH authentication for GitHub repos make for easier authentication, IME
* Avoiding OS Specific credential helpers, which have been flaky over the years
* Verification reduces the likelihood of someone anonymously joining the team and raising a ruckus.

**Comment by Githubbubber** [comment]
> Here are two reasons for people to verify:
> 
> * SSH authentication for GitHub repos make for easier authentication, IME
> * Avoiding OS Specific credential helpers, which have been flaky over the years
> * Verification reduces the likelihood of someone anonymously joining the team and raising a ruckus.

I will add these points to the spike.

**Comment by Githubbubber** [comment]
@mnyon-grandkru thx for the recs! Noted in the doc itself, in the [pr](https://github.com/QueerGlobal/qg-docs/pull/7)

**Comment by Githubbubber** [comment]
PR submitted for review
